[package]
name = "actions-telegram-notifier"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.133"
reqwest = { version = "0.12.9", features = ["blocking", "json"] }
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
